variables:
  - &rust_image "rust:1.81.0"

steps:
  cargo_fmt:
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  toml_fmt:
    group: format
    image: tamasfe/taplo:0.8.1
    commands:
      - taplo format --check

  cargo_check:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo check --all-features --all-targets

  cargo_clippy:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - rustup component add clippy
      - cargo clippy

  cargo_test:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo test --all-features --no-fail-fast

  cargo_run:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run
