[package]
name = "generate-dev-update"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
itertools = "0.13.0"
lemmy_api_common = "0.19.5"
octocrab = "0.41.0"
reqwest = { version = "0.12.7", default-features = false, features = [
  "rustls-tls",
  "json",
] }
rustls = { version = "0.23.15", default-features = false }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
