[package]
name = "generate-dev-update"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
itertools = "0.13.0"
octocrab = "0.40.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
